#zf210731.2214
#source: https://www.home-assistant.io/integrations/facebox/

version: '3.2'
services:
  facebox:
    image: machinebox/facebox:latest
    environment:
#      - MB_BASICAUTH_USER=toto
#      - MB_BASICAUTH_PASS=tutu
      - MB_KEY=$MB_KEY
      - MB_FACEBOX_DISABLE_RECOGNITION=false
    ports:
      - 8089:8080

